// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPlJk5jboKqP4Qx22o0c8mGVwAv-2SdJc',
    appId: '1:1065352815147:web:221d427d1de6484c7c406e',
    messagingSenderId: '1065352815147',
    projectId: 'fir-101-81a8b',
    authDomain: 'fir-101-81a8b.firebaseapp.com',
    storageBucket: 'fir-101-81a8b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCg8CkYVRLwiRnydC_WhtynzAFgXZbtCxs',
    appId: '1:1065352815147:android:cfa71d8c908f1ac67c406e',
    messagingSenderId: '1065352815147',
    projectId: 'fir-101-81a8b',
    storageBucket: 'fir-101-81a8b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGT_F_1dtJRZjPILjp53bKa7pJf4yaBiE',
    appId: '1:1065352815147:ios:24f4965418ca2e157c406e',
    messagingSenderId: '1065352815147',
    projectId: 'fir-101-81a8b',
    storageBucket: 'fir-101-81a8b.firebasestorage.app',
    iosBundleId: 'com.example.motionFlutterFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGT_F_1dtJRZjPILjp53bKa7pJf4yaBiE',
    appId: '1:1065352815147:ios:24f4965418ca2e157c406e',
    messagingSenderId: '1065352815147',
    projectId: 'fir-101-81a8b',
    storageBucket: 'fir-101-81a8b.firebasestorage.app',
    iosBundleId: 'com.example.motionFlutterFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAPlJk5jboKqP4Qx22o0c8mGVwAv-2SdJc',
    appId: '1:1065352815147:web:016d25a174ee78827c406e',
    messagingSenderId: '1065352815147',
    projectId: 'fir-101-81a8b',
    authDomain: 'fir-101-81a8b.firebaseapp.com',
    storageBucket: 'fir-101-81a8b.firebasestorage.app',
  );

}